development:
  AWS_ACCESS_KEY_ID: 'AKIAJIZNPGYJGUJWEDFA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'profile-pics123-dev'

test:
  AWS_ACCESS_KEY_ID: 'AKIAJIZNPGYJGUJWEDFA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'profile-pics123-test'

production:
  AWS_ACCESS_KEY_ID: 'AKIAJIZNPGYJGUJWEDFA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'profile-pics123-production'
